### ISSUE TITLE
Не работают субтитры (Kodi 16.1 Jarvis RC2)

### ISSUE THREAD

**Issue by lukegluke** [IH8E/plugin.video.lalapaluza#1]
Ссылку вытягивает правильную (print 'Субтиты',ss), но субтитры к видео не подключает. 

Скорее всего http://forum.kodi.tv/showthread.php?tid=265777 поможет в решении проблемы.
Вот здесь http://www.programcreek.com/python/example/18039/xbmc.Player примеры (в частности Example 14), которые также могут помочь.

Спасибо!

**Comment by IH8E** [comment]
Наконец-то добрался, сейчас субтитры для каждой серии загружаются в директорию аддона/subs. 

Буду рад новым предложениям и пожеланиям.
